[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sagrel <Sagrel@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rayon = "1.5.1"
image = "0.24.1"
optick = "1.3.4"
indicatif = "0.16.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
debug = 1